# Generated by Django 5.0.1 on 2024-02-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
