# Generated by Django 5.0.1 on 2024-02-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Name',
            field=models.CharField(max_length=255),
        ),
    ]
