# Generated by Django 5.0.1 on 2024-02-11 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='No_of_guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
